# Change these first
owner: mh-data-science # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Prod Barracuda v3
    url: https://barracuda.mhtr.be/v3/docs
  - name: Prod Barracuda v2
    url: https://barracuda.mhtr.be/v2/docs
  - name: UAT Barracuda v3
    url: https://barracuda-uat.mhtr.be/v3/docs
  - name: UAT Barracuda v2
    url: https://barracuda-uat.mhtr.be/v2/docs
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GLaMR Upptime
  introTitle: GLaMR Status
  introMessage: See the status of various sites in the GLaMR ecosystem
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
